#!/usr/bin/env bash
# A Bash script that groups visitors by IP and HTTP status code, and displays this data.
# The exact format must be OCCURENCE_NUMBER IP HTTP_CODE and in list format
# Ordered from the greatest to the lowest number of occurrences

if test -f $apache-access.log
then
	awk '{print $1,$9}' $apache-access.log | sort | uniq -c | sort -gr
fi
