#!/usr/bin/env bash
# A Bash script that groups visitors by IP and HTTP status code, and displays this data.
# The exact format must be OCCURENCE_NUMBER IP HTTP_CODE and in list format
# Ordered from the greatest to the lowest number of occurrences

file="apache-access.log"
if test -f $file
then
	awk '{print $1, $9}' $file | sort | uniq -c | sort -gr
fi
