#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 displaying
#+ "bad luck", "good luck" and "Best School"

a=1
while [ $a -le 10 ]
do 
	if [ $a -eq 4 ]
	then
		echo "bad luck"	
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((a++))
done
