#!/usr/bin/env bash
# A Bash script that gives you information about the school file.

if [ -e "school" ]
then
	echo "school file exists"
	if [ -e "school" ]
	then
		echo "school file does not exist"
	else
	then
		echo "school file is empty"
	fi

if [ -f "school" ]
then
	echo "school file is not empty"
fi
else
	echo "school is a regular file"
fi
